site_name: Large Language Models Course @ Inha University
site_url: https://gcl-inha.github.io/ece7115
theme:
  name: material
  custom_dir: overrides
  features: []
  font:
    text: Montserrat
  primary: custom
  logo: assets/logo_gcl_white.png
  favicon: assets/logo_gcl.png

nav:
  - Home: index.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  homepage: https://gcl-inha.github.io
  alternate:
    - name: 🇰🇷 <span class="lg-txt">한국어</span>
      link: /ece7115/
      lang: ko
    - name: 🇺🇸 <span class="lg-txt">English</span>
      link: /ece7115/en/
      lang: en

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ko
          default: true
          name: 한국어
          build: true
        - locale: en
          name: English
          build: true
  - macros:
      include_yaml:
        - schedule: data/schedule.yml

copyright: Copyright &copy; 2025 -  Generative Computing Lab at Inha University
